services:
  services:
  wordpress:
    image: wordpress:php7.4-apache
    volumes:
      - ./src:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: my_database
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: tiger
      WORDPRESS_DEBUG: 0
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:80"
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  db-data: