services:
  php:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - phpdb
    networks:
      - app-network
    env_file: .env

  phpdb:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - phpdb-data5:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network
    env_file: .env

networks:
  app-network:
    driver: bridge

volumes:
  phpdb-data5:
