services:
  wordpress:
    image: wordpress:php7.4-apache
    volumes:
       - ./src/wp-content:/var/www/html/wp-content
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: my_database
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: tiger
      WORDPRESS_DEBUG: 0
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:80"
    networks:
      - app-network
    restart: unless-stopped

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: tiger
      MYSQL_DATABASE: my_database
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "exit | mysql -h localhost -P 3306 -u root -p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  app-network:
    driver: bridge

volumes:
  db-data: