services:
  php:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html/
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: tiger
      MYSQL_DATABASE: my_database
    ports:
      - "3306:3306"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge

volumes:
  db-data:
