services:
  php:
    build: .
    ports:
      - '8080:80'
    volumes:
      - ./src:/var/www/html/
    depends_on:
      - db
    networks:
      - app-network
      - dokploy-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.phptodolist.rule=Host(`sklawik.pl`)
      - traefik.http.routers.phptodolist.entrypoints=web
      - traefik.http.services.phptodolist.loadbalancer.server.port=80

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: tiger
      MYSQL_DATABASE: my_database
    volumes:
      - db-data2:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
  dokploy-network:
    external: true

volumes:
  db-data2: