

services:
  php:
    build: .
    volumes:
      - ./src:/var/www/html 
    depends_on:
      - db  

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: tiger
      MYSQL_DATABASE: my_database
    volumes:
      - db-data:/var/lib/mysql  
    ports:
      - "3306:3306" 

volumes:
  db-data: